production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  stripe_sync:
    class: StripeSyncJob
    schedule: every day at 3am UTC

  monthly_snapshot:
    class: MonthlySnapshotJob
    schedule: every day at 4am UTC
